services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  JWeiland\Avalex\:
    resource: '../Classes/*'

  cache.avalexContent:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['avalex_content']

  cache.avalexLanguages:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['avalex_languages']

  flashMessageQueue:
    class: TYPO3\CMS\Core\Messaging\FlashMessageQueue
    factory: ['@TYPO3\CMS\Core\Messaging\FlashMessageService', 'getMessageQueueByIdentifier']

  querybuilder.tx_avalex_configuration:
    class: 'TYPO3\CMS\Core\Database\Query\QueryBuilder'
    factory:
      - '@TYPO3\CMS\Core\Database\ConnectionPool'
      - 'getQueryBuilderForTable'
    arguments:
      - 'tx_avalex_configuration'

  JWeiland\Avalex\Backend\Preview\ContentPreviewRenderer:
    public: true

  JWeiland\Avalex\Domain\Repository\AvalexConfigurationRepository:
    arguments:
      $queryBuilder: '@querybuilder.tx_avalex_configuration'

  JWeiland\Avalex\Client\Request\Endpoint\BedingungenRequest:
    public: true
    tags:
      - name: 'avalex.request'

  JWeiland\Avalex\Client\Request\Endpoint\DatenschutzerklaerungRequest:
    public: true
    tags:
      - name: 'avalex.request'

  JWeiland\Avalex\Client\Request\Endpoint\GetDomainLanguagesRequest:
    public: true
    tags:
      - name: 'avalex.request'

  JWeiland\Avalex\Client\Request\Endpoint\ImpressumRequest:
    public: true
    tags:
      - name: 'avalex.request'

  JWeiland\Avalex\Client\Request\Endpoint\IsApiKeyConfiguredRequest:
    public: true
    tags:
      - name: 'avalex.request'

  JWeiland\Avalex\Client\Request\Endpoint\WiderrufRequest:
    public: true
    tags:
      - name: 'avalex.request'

  JWeiland\Avalex\Client\Request\RequestFactory:
    arguments:
      $registeredAvalexRequests: !tagged_iterator { tag: 'avalex.request' }

  JWeiland\Avalex\Client\AvalexClient:
    public: true

  JWeiland\Avalex\Hook\DataHandlerHook:
    public: true
    arguments:
      $flashMessageQueue: '@flashMessageQueue'

  JWeiland\Avalex\Service\ApiService:
    arguments:
      $cache: '@cache.avalexContent'

  JWeiland\Avalex\Service\LanguageService:
    arguments:
      $cache: '@cache.avalexLanguages'

  JWeiland\Avalex\AvalexPlugin:
    public: true
