services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  JWeiland\Avalex\:
    resource: '../Classes/*'

  JWeiland\Avalex\Backend\Preview\ContentPreviewRenderer:
    public: true
  JWeiland\Avalex\Client\AvalexClient:
    public: true
  JWeiland\Avalex\Client\Request\BedingungenRequest:
    public: true
  JWeiland\Avalex\Client\Request\DatenschutzerklaerungRequest:
    public: true
  JWeiland\Avalex\Client\Request\ImpressumRequest:
    public: true
  JWeiland\Avalex\Client\Request\WiderrufRequest:
    public: true
  JWeiland\Avalex\Hook\DataHandlerHook:
    public: true
