name: Tests

on: [pull_request]

jobs:
  testing:
    name: Testing

    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

      matrix:
        php:
          - '8.2'
          - '8.3'
          - '8.4'

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Lint PHP'
        run: Build/Scripts/runTests.sh -b podman -p ${{ matrix.php }} -s lint

      - name: 'Install testing system'
        run: Build/Scripts/runTests.sh -b podman -p ${{ matrix.php }} -s composerUpdate

      - name: 'Composer validate'
        run: Build/Scripts/runTests.sh -b podman -p ${{ matrix.php }} -s composerValidate

      - name: 'Composer normalize'
        run: Build/Scripts/runTests.sh -b podman -p ${{ matrix.php }} -s composerNormalize -n

      - name: 'CGL'
        if: ${{ matrix.php <= '8.3' }}
        run: Build/Scripts/runTests.sh -b podman -n -p ${{ matrix.php }} -s cgl

      - name: 'Execute functional tests'
        run: Build/Scripts/runTests.sh -b podman -p ${{ matrix.php }} -d mysql -i 8.0 -s functional

      - name: 'Execute functional tests'
        run: Build/Scripts/runTests.sh -b podman -p ${{ matrix.php }} -d mariadb -i 10.4 -s functional

      - name: 'Execute functional tests'
        run: Build/Scripts/runTests.sh -b podman -p ${{ matrix.php }} -d postgres -i 10 -s functional
