name: Test Avalex against TYPO3 version 11 - 12

on: [pull_request]

jobs:
  CGL:
    name: Coding Style

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        run: Build/Scripts/runTests.sh -t 11 -p 8.1 -s composer -e 'validate'

      - name: Install testing system
        run: Build/Scripts/runTests.sh -t 11 -p ${{ matrix.php }} -s composerInstall

      - name: Lint PHP
        run: Build/Scripts/runTests.sh -t 11 -p 8.1 -s lint

      - name: Validate code against CGL
        run: Build/Scripts/runTests.sh -t 11 -p 8.1 -s cgl -n

  testing:
    name: PHP Unit and Functional Tests
    needs: CGL

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        php: [ '7.4', '8.0', '8.1' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install testing system
        run: Build/Scripts/runTests.sh -t 11 -p ${{ matrix.php }} -s composerInstall

      - name: Functional Tests with mariadb and mysqli
        run: Build/Scripts/runTests.sh -t 11 -p ${{ matrix.php }} -d mariadb -a mysqli -s functional
